input {
  rabbitmq {
    host => "rabbitmq"
    port => 5672
    user => "guest"
    password => "guest"
    queue => "telemetria.ingestao"
    durable => true
    codec => "json"
  }
}

filter {
  date {
    match => ["momentoDaLeitura", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    convert => {
      "latitude" => "float"
      "longitude" => "float"
      "velocidadeEmQuilometrosPorHora" => "float"
      "temperaturaDoMotorEmGrausCelsius" => "float"
      "nivelDeCombustivelEmPercentual" => "float"
    }
  }

  mutate {
    add_field => {
      "localizacao" => "%{latitude},%{longitude}"
    }
  }

  translate {
    source => "categoria"
    target => "descricaoDaCategoria"
    dictionary => {
      "Utilitario" => "Utilitário"
      "CargaPesada" => "Carga Pesada"
      "Passeio" => "Passeio"
      "Motocicleta" => "Motocicleta"
    }
    fallback => "Desconhecida"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "telemetria-frota-%{+YYYY.MM.dd}"
    manage_template => false
    ilm_enabled => false
  }
}
